{% set version = "1.3.6" %}

package:
  name: nomino
  version: {{ version }}

source:
  url: https://github.com/yaa110/nomino/archive/{{ version }}.tar.gz
  sha256: 12e14d951b3fa99d17b9a0de97b7f9d9003f67ef83eb6b993623da066bc54dd4

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses

test:
  commands:
    - nomino --help

about:
  home: https://github.com/yaa110/nomino
  dev_url: https://github.com/yaa110/nomino
  license: MIT
  license_family: MIT
  license_file: LICENSE-MIT
  summary: Batch rename utility for developers

extra:
  recipe-maintainers:
    - apcamargo
