{% set version = "1.5.2" %}

package:
  name: nomino
  version: {{ version }}

source:
  url: https://github.com/yaa110/nomino/archive/{{ version }}.tar.gz
  sha256: 728a6a05249210ca1475e686b756af1666597c738763b21de62a8e3428c954e9

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses

test:
  commands:
    - nomino --help

about:
  home: https://github.com/yaa110/nomino
  dev_url: https://github.com/yaa110/nomino
  license: MIT
  license_family: MIT
  license_file: LICENSE-MIT
  summary: Batch rename utility for developers

extra:
  recipe-maintainers:
    - apcamargo
