{% set version = "1.4.0" %}

package:
  name: nomino
  version: {{ version }}

source:
  url: https://github.com/yaa110/nomino/archive/{{ version }}.tar.gz
  sha256: 4b0e1debd76995b60ad020db97431ffcc01a64d4fc0040702ef0dea7ea368536

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses

test:
  commands:
    - nomino --help

about:
  home: https://github.com/yaa110/nomino
  dev_url: https://github.com/yaa110/nomino
  license: MIT
  license_family: MIT
  license_file: LICENSE-MIT
  summary: Batch rename utility for developers

extra:
  recipe-maintainers:
    - apcamargo
